name: Build
'on':
    release:
        types:
            - published

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: 'mbstring, fileinfo'
                  tools: composer

            - name: Install dependencies
              run: composer install --no-dev --prefer-dist

            - name: Build PHAR using Laravel Zero
              run: 'php librarian app:build --build-version="${{ github.ref_name }}"'

            - name: Upload PHAR to release
              uses: softprops/action-gh-release@v1
              with:
                  files: builds/librarian
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
