name: Tests
'on':
    push:
        branches:
            - main
    workflow_dispatch: null
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php:
                    - 8.2
                    - 8.3
                    - 8.4
        name: 'PHP ${{ matrix.php }}'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php }}'
                  extensions: 'mbstring, fileinfo'
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              run: php librarian test
